# Generated by Django 3.2.2 on 2021-05-13 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='sub_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(),
        ),
    ]
